"use client";
import { useInfiniteQuery, useMutation, useQueryClient, type InfiniteData } from "@tanstack/react-query";
import Image from "next/image";
import { useRouter } from "next/navigation";
import { useCallback, useEffect, useRef, useState } from "react";
import { useAuth } from "@/features/auth/AuthProvider";
import type { User } from "@/features/auth/types";
import { feedKeys, feedRepository } from "../repository";
import type { Comment, FeedUser, Liker, Page, Post, Visibility } from "../types";
import { uploadPostImage } from "../upload";

const fullName = (user: Pick<User, "firstName" | "lastName">) => `${user.firstName} ${user.lastName}`;
const relativeTime = (date: string) => { const minutes = Math.max(1, Math.round((Date.now() - Date.parse(date)) / 60_000)); if (minutes < 60) return `${minutes}m`; const hours = Math.round(minutes / 60); return hours < 24 ? `${hours}h` : `${Math.round(hours / 24)}d`; };
function Avatar({ user, size = 42 }: { user: FeedUser; size?: number }) { return user.avatarUrl ? <Image className="avatar" src={user.avatarUrl} alt={`${fullName(user)}'s avatar`} width={size} height={size} /> : <span className="avatar avatar-fallback" style={{ width: size, height: size }} aria-label={`${fullName(user)}'s avatar`}>{user.firstName[0]}{user.lastName[0]}</span>; }

function ThemeToggle() { const [dark, setDark] = useState(false); useEffect(() => { const frame = requestAnimationFrame(() => { const saved = localStorage.getItem("buddy-theme"); const next = saved ? saved === "dark" : matchMedia("(prefers-color-scheme: dark)").matches; setDark(next); document.documentElement.dataset.theme = next ? "dark" : "light"; }); return () => cancelAnimationFrame(frame); }, []); const toggle = () => { const next = !dark; setDark(next); document.documentElement.dataset.theme = next ? "dark" : "light"; localStorage.setItem("buddy-theme", next ? "dark" : "light"); }; return <button type="button" className="theme-toggle" role="switch" aria-checked={dark} onClick={toggle}><span>☀</span><i className={dark ? "active" : ""} /><span>☾</span><span className="sr-only">Use dark theme</span></button>; }

function Header({ user }: { user: FeedUser }) { const auth = useAuth(); const router = useRouter(); const [open, setOpen] = useState(false); const logout = async () => { await auth.logout(); router.replace("/login"); }; return <header className="site-header"><div className="header-inner"><Image src="/assets/logo.svg" alt="BuddyScript" width={170} height={40} priority /><label className="header-search"><span>⌕</span><input type="search" placeholder="Input search text" disabled aria-label="Search is not available" /></label><nav aria-label="Primary navigation"><button className="nav-active" aria-label="Home">⌂</button><button disabled aria-label="Friends unavailable">♧</button><button disabled aria-label="Notifications unavailable">♢</button><button disabled aria-label="Messages unavailable">□</button></nav><div className="profile-menu"><button type="button" onClick={() => setOpen(!open)} aria-expanded={open}><Avatar user={user} size={38} /><span>{user.firstName}</span><span>⌄</span></button>{open && <div className="profile-dropdown"><strong>{fullName(user)}</strong><button type="button" onClick={logout}>Log out</button></div>}</div></div></header>; }

function Sidebars({ user }: { user: FeedUser }) { return <><aside className="left-sidebar"><div className="profile-card"><Avatar user={user} size={70} /><h2>{fullName(user)}</h2><p>BuddyScript community member</p></div><nav>{["Feed", "My community", "Messages", "Notifications", "Explore", "Saved posts"].map((label, index) => <button type="button" key={label} disabled={index > 0} className={index === 0 ? "active" : ""}>{label}</button>)}</nav><div className="event-card"><Image src="/assets/feed_event1.png" alt="Design meetup event" width={260} height={175} /><strong>Design systems meetup</strong></div></aside><aside className="right-sidebar"><section><div className="section-heading"><h2>Your Friends</h2><button disabled>See All</button></div>{["Ryan Roslansky", "Dylan Field", "Radovan SkillArena"].map((name, index) => <div className="people-row" key={name}><Image className="avatar" src={`/assets/${["people2.png", "people3.png", "Avatar.png"][index]}`} alt="" width={44} height={44} /><span><strong>{name}</strong><small>BuddyScript community</small></span></div>)}</section></aside></>; }
function Stories() { return <section className="stories" aria-label="Stories"><button disabled className="story-create"><span>+</span><small>Create Story</small></button>{["card_ppl1.png", "card_ppl2.png", "card_ppl3.png", "card_ppl4.png"].map((asset, index) => <button disabled className="story" key={asset}><Image src={`/assets/${asset}`} alt="" fill sizes="120px" /><small>{["Karim", "Dylan", "Ryan", "Ava"][index]}</small></button>)}</section>; }

function Composer({ user }: { user: FeedUser }) {
  const client = useQueryClient(); const [body, setBody] = useState(""); const [visibility, setVisibility] = useState<Visibility>("public"); const [file, setFile] = useState<File>(); const [preview, setPreview] = useState<string>(); const [progress, setProgress] = useState(0); const [error, setError] = useState(""); const abortRef = useRef<AbortController | undefined>(undefined);
  useEffect(() => () => { if (preview) URL.revokeObjectURL(preview); abortRef.current?.abort(); }, [preview]);
  const mutation = useMutation({ mutationFn: async () => { const controller = new AbortController(); abortRef.current = controller; const image = file ? await uploadPostImage(file, setProgress, controller.signal) : undefined; return feedRepository.create({ ...(body.trim() ? { body: body.trim() } : {}), visibility, ...(image ? { image } : {}) }); }, onSuccess: async () => { setBody(""); setFile(undefined); if (preview) URL.revokeObjectURL(preview); setPreview(undefined); setProgress(0); await client.invalidateQueries({ queryKey: feedKeys.all }); }, onError: (cause) => setError(cause instanceof Error ? cause.message : "Post creation failed.") });
  const choose = (selected?: File) => { setError(""); if (!selected) return; if (!["image/jpeg", "image/png", "image/webp"].includes(selected.type) || selected.size > 5_000_000) { setError("Choose a JPG, PNG, or WebP image smaller than 5 MB."); return; } if (preview) URL.revokeObjectURL(preview); setFile(selected); setPreview(URL.createObjectURL(selected)); };
  return <section className="composer"><div className="composer-top"><Avatar user={user} /><textarea value={body} onChange={(event) => setBody(event.target.value)} placeholder="Write something ..." aria-label="Post text" maxLength={5000} /></div>{preview && <div className="image-preview"><Image src={preview} alt="Selected post preview" width={700} height={400} unoptimized /><button type="button" onClick={() => { URL.revokeObjectURL(preview); setPreview(undefined); setFile(undefined); }}>×</button></div>}<div className="composer-bottom"><div><label className="composer-photo">▧ <span>Photo</span><input hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => choose(event.target.files?.[0])} /></label><button disabled>▷ <span>Video</span></button><button disabled>▦ <span>Event</span></button></div><label className="visibility"><span className="sr-only">Post visibility</span><select value={visibility} onChange={(event) => setVisibility(event.target.value as Visibility)}><option value="public">Public</option><option value="private">Private</option></select></label><button className="post-button" type="button" disabled={mutation.isPending || (!body.trim() && !file)} onClick={() => mutation.mutate()}>➤ {mutation.isPending ? file && progress < 100 ? `Uploading ${progress}%` : "Posting" : "Post"}</button>{mutation.isPending && <button type="button" onClick={() => abortRef.current?.abort()}>Cancel</button>}</div>{error && <p className="composer-error" role="alert">{error}</p>}</section>;
}

function CommentForm({ placeholder, submit }: { placeholder: string; submit: (body: string) => Promise<void> }) { const [body, setBody] = useState(""); const [pending, setPending] = useState(false); return <form className="comment-form" onSubmit={async (event) => { event.preventDefault(); if (!body.trim()) return; setPending(true); await submit(body.trim()).finally(() => setPending(false)); setBody(""); }}><input value={body} onChange={(event) => setBody(event.target.value)} placeholder={placeholder} aria-label={placeholder} /><button disabled={pending || !body.trim()}>➤</button></form>; }

function CommentItem({ comment, showLikers }: { comment: Comment; showLikers: (commentId: string) => void }) { const client = useQueryClient(); const [replying, setReplying] = useState(false); const replies = useInfiniteQuery({ queryKey: feedKeys.replies(comment.id), queryFn: ({ pageParam }) => feedRepository.replies(comment.id, pageParam), initialPageParam: undefined as string | undefined, getNextPageParam: (page) => page.nextCursor ?? undefined, enabled: comment.depth === 0 && (replying || comment.engagement.replyCount > 0) }); const reaction = useMutation({ mutationFn: () => feedRepository.setCommentLike(comment.id, !comment.engagement.likedByViewer), onSuccess: () => client.invalidateQueries({ queryKey: comment.parentId ? feedKeys.replies(comment.parentId) : ["comments", comment.postId] }) }); const add = async (body: string) => { await feedRepository.addReply(comment.id, body); await client.invalidateQueries({ queryKey: feedKeys.replies(comment.id) }); setReplying(false); }; return <div className={`comment ${comment.depth ? "reply" : ""}`}><Avatar user={comment.author} size={36} /><div className="comment-content"><div className="comment-bubble"><strong>{fullName(comment.author)}</strong><p>{comment.body}</p></div><div className="comment-actions"><button type="button" onClick={() => reaction.mutate()}>{comment.engagement.likedByViewer ? "Unlike" : "Like"}</button>{comment.depth === 0 && <button type="button" onClick={() => setReplying(!replying)}>Reply</button>}<span>{relativeTime(comment.createdAt)}</span><button type="button" onClick={() => showLikers(comment.id)}>♥ {comment.engagement.likeCount}</button></div>{comment.depth === 0 && <>{replies.data?.pages.flatMap((page) => page.items).map((reply) => <CommentItem key={reply.id} comment={reply} showLikers={showLikers} />)}{replies.hasNextPage && <button type="button" onClick={() => replies.fetchNextPage()}>Load more replies</button>}{replying && <CommentForm placeholder={`Reply to ${comment.author.firstName}…`} submit={add} />}</>}</div></div>; }

function Comments({ post, showLikers }: { post: Post; showLikers: (commentId: string) => void }) { const client = useQueryClient(); const [expanded, setExpanded] = useState(false); const comments = useInfiniteQuery({ queryKey: feedKeys.comments(post.id), queryFn: ({ pageParam }) => feedRepository.comments(post.id, pageParam), initialPageParam: undefined as string | undefined, getNextPageParam: (page) => page.nextCursor ?? undefined, enabled: expanded }); const items = expanded ? comments.data?.pages.flatMap((page) => page.items) ?? [] : post.commentPreview; const add = async (body: string) => { await feedRepository.addComment(post.id, body); setExpanded(true); await Promise.all([client.invalidateQueries({ queryKey: feedKeys.comments(post.id) }), client.invalidateQueries({ queryKey: feedKeys.all })]); }; return <div className="comments"><CommentForm placeholder="Write a comment" submit={add} />{post.engagement.commentCount > post.commentPreview.length && <button type="button" className="previous-comments" onClick={() => setExpanded(true)}>View all {post.engagement.commentCount} comments</button>}{comments.isLoading && <p>Loading comments…</p>}{items.map((comment) => <CommentItem key={comment.id} comment={comment} showLikers={showLikers} />)}{comments.hasNextPage && <button type="button" onClick={() => comments.fetchNextPage()}>Load more comments</button>}</div>; }

function LikersDialog({ target, close }: { target: { kind: "post" | "comment"; id: string }; close: () => void }) { const ref = useRef<HTMLDialogElement>(null); const query = useInfiniteQuery({ queryKey: feedKeys.likers(target.kind, target.id), queryFn: ({ pageParam }) => target.kind === "post" ? feedRepository.postLikers(target.id, pageParam) : feedRepository.commentLikers(target.id, pageParam), initialPageParam: undefined as string | undefined, getNextPageParam: (page) => page.nextCursor ?? undefined }); useEffect(() => ref.current?.showModal(), []); const users: Liker[] = query.data?.pages.flatMap((page) => page.items) ?? []; return <dialog ref={ref} className="likers-dialog" onClose={close}><div className="dialog-title"><h2>Liked by</h2><button onClick={() => ref.current?.close()}>×</button></div>{query.isLoading ? <p>Loading…</p> : users.length ? <ul>{users.map((user) => <li key={`${user.id}-${user.likedAt}`}><Avatar user={user} /><strong>{fullName(user)}</strong></li>)}</ul> : <p>No likes yet.</p>}{query.hasNextPage && <button onClick={() => query.fetchNextPage()}>Load more</button>}</dialog>; }

function PostCard({ post, showLikers, showCommentLikers }: { post: Post; showLikers: () => void; showCommentLikers: (commentId: string) => void }) {
  const client = useQueryClient();
  const mutation = useMutation({
    mutationFn: () => feedRepository.setPostLike(post.id, !post.engagement.likedByViewer),
    onMutate: async () => {
      await client.cancelQueries({ queryKey: feedKeys.all }); const previous = client.getQueryData<InfiniteData<Page<Post>>>(feedKeys.all);
      client.setQueryData<InfiniteData<Page<Post>>>(feedKeys.all, (data) => data && ({ ...data, pages: data.pages.map((page) => ({ ...page, items: page.items.map((item) => item.id === post.id ? { ...item, engagement: { ...item.engagement, likedByViewer: !item.engagement.likedByViewer, likeCount: Math.max(0, item.engagement.likeCount + (item.engagement.likedByViewer ? -1 : 1)) } } : item) })) }));
      return previous;
    },
    onError: (_error, _variables, previous) => client.setQueryData(feedKeys.all, previous), onSettled: () => client.invalidateQueries({ queryKey: feedKeys.all }),
  });
  return <article className="post-card"><div className="post-head"><Avatar user={post.author} /><div><h2>{fullName(post.author)}</h2><p>{relativeTime(post.createdAt)} · {post.visibility === "public" ? "Public" : "Private"}</p></div></div>{post.body && <p className="post-body">{post.body}</p>}{post.image && <div className="post-image"><Image src={post.image.secureUrl} alt="Image shared with this post" width={post.image.width} height={post.image.height} /></div>}<div className="post-stats"><button type="button" onClick={showLikers}>♥ {post.engagement.likeCount} {post.engagement.likeCount === 1 ? "person" : "people"}</button><span>{post.engagement.commentCount} Comments</span></div><div className="post-actions"><button type="button" disabled={mutation.isPending} className={post.engagement.likedByViewer ? "liked" : ""} onClick={() => mutation.mutate()}>♡ {post.engagement.likedByViewer ? "Unlike" : "Like"}</button><button type="button">▢ Comment</button><button disabled>⌁ Share</button></div><Comments post={post} showLikers={showCommentLikers} /></article>;
}

export function FeedApp() { const auth = useAuth(); const [likers, setLikers] = useState<{ kind: "post" | "comment"; id: string }>(); const query = useInfiniteQuery({ queryKey: feedKeys.all, queryFn: ({ pageParam }) => feedRepository.list(pageParam), initialPageParam: undefined as string | undefined, getNextPageParam: (page) => page.nextCursor ?? undefined }); const posts = Array.from(new Map((query.data?.pages.flatMap((page) => page.items) ?? []).map((post) => [post.id, post])).values()); const refresh = useCallback(() => query.refetch(), [query]); if (auth.status !== "authenticated") return null; return <div className="feed-app"><ThemeToggle /><Header user={auth.user} /><div className="feed-layout"><Sidebars user={auth.user} /><main className="feed-main"><Stories /><Composer user={auth.user} />{query.isLoading ? <div className="feed-loading"><p>Loading your feed…</p></div> : query.isError ? <div className="feed-error"><p>We could not load your feed.</p><button onClick={() => refresh()}>Try again</button></div> : posts.length ? <>{posts.map((post) => <PostCard key={post.id} post={post} showLikers={() => setLikers({ kind: "post", id: post.id })} showCommentLikers={(id) => setLikers({ kind: "comment", id })} />)}{query.hasNextPage && <button className="load-more" onClick={() => query.fetchNextPage()} disabled={query.isFetchingNextPage}>{query.isFetchingNextPage ? "Loading…" : "Load more posts"}</button>}</> : <div className="feed-empty"><h2>Your feed is quiet</h2><p>Create the first post.</p></div>}</main></div>{likers && <LikersDialog target={likers} close={() => setLikers(undefined)} />}</div>; }
